# Generated by Django 5.1.7 on 2025-03-26 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Scraper', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scrape',
            name='address',
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
    ]
