# Generated by Django 5.1.7 on 2025-03-26 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Scraper', '0003_rename_scrape_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='link',
            name='name',
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
    ]
